remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: [GnuPG Keys Management]
description: [Personal approach of GnuPG understanding and Keys management walkthrough]
author: "Gwenall Pansier"


  #social:
  #  github: gwenall
  #  linkedin: gwenall
  #  twitter: _gwenall
  #  email: gwenall.pansier+git@my-cloud.me
  #  gpg: https://keybase.io/gwenall/pgp_keys.asc
  #  stackoverflow: ''


# remove dates and prettify links
permalink: pretty

